server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webchat?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/static/
shiro:
  loginUrl: /login.html

mybatis:
  #映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #模型所在的包名
  type-aliases-package: com.coco.demo.socketdemo.entity

